export const data = [
  {
    id: 1,
    name: 'Idly 1',
    category: 'Idly',
    restaurant: 'Foodie Hub',
    price: 11.53,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/idly/idly44.jpg',
  },
  {
    id: 2,
    name: 'Pasta 2',
    category: 'Pasta',
    restaurant: 'Belly Bliss',
    price: 5.04,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/pasta/pasta12.jpg',
  },
  {
    id: 3,
    name: 'Burger 3',
    category: 'Burger',
    restaurant: 'Foodie Hub',
    price: 12.69,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/burger/burger23.jpg',
  },
  {
    id: 4,
    name: 'Dessert 4',
    category: 'Dessert',
    restaurant: 'Urban Kitchen',
    price: 17.26,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/dessert/dessert31.jpg',
  },
  {
    id: 5,
    name: 'Burger 5',
    category: 'Burger',
    restaurant: 'Foodie Hub',
    price: 16.42,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/burger/burger29.jpg',
  },
  {
    id: 6,
    name: 'Dosa 6',
    category: 'Dosa',
    restaurant: 'Delish Diner',
    price: 19.15,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/dosa/dosa26.jpg',
  },
  {
    id: 7,
    name: 'Dosa 7',
    category: 'Dosa',
    restaurant: 'Tasty Bites',
    price: 15.7,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/dosa/dosa47.jpg',
  },
  {
    id: 8,
    name: 'Burger 8',
    category: 'Burger',
    restaurant: 'Urban Kitchen',
    price: 7.48,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/burger/burger31.jpg',
  },
  {
    id: 9,
    name: 'Pasta 9',
    category: 'Pasta',
    restaurant: 'Belly Bliss',
    price: 12.4,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/pasta/pasta22.jpg',
  },
  {
    id: 10,
    name: 'Biryani 10',
    category: 'Biryani',
    restaurant: 'Foodie Hub',
    price: 19.85,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/biryani/biryani45.jpg',
  },
  {
    id: 11,
    name: 'Pizza 11',
    category: 'Pizza',
    restaurant: 'Delish Diner',
    price: 19.61,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/pizza/pizza1.jpg',
  },
  {
    id: 12,
    name: 'Pizza 12',
    category: 'Pizza',
    restaurant: 'Belly Bliss',
    price: 10.84,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/pizza/pizza6.jpg',
  },
  {
    id: 13,
    name: 'Rice 13',
    category: 'Rice',
    restaurant: 'Foodie Hub',
    price: 14.52,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/rice/rice41.jpg',
  },
  {
    id: 14,
    name: 'Biryani 14',
    category: 'Biryani',
    restaurant: 'Delish Diner',
    price: 15.01,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/biryani/biryani24.jpg',
  },
  {
    id: 15,
    name: 'Pizza 15',
    category: 'Pizza',
    restaurant: 'Tasty Bites',
    price: 8.7,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/pizza/pizza9.jpg',
  },
  {
    id: 16,
    name: 'Biryani 16',
    category: 'Biryani',
    restaurant: 'Tasty Bites',
    price: 11.46,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/biryani/biryani18.jpg',
  },
  {
    id: 17,
    name: 'Pasta 17',
    category: 'Pasta',
    restaurant: 'Delish Diner',
    price: 10.31,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/pasta/pasta25.jpg',
  },
  {
    id: 18,
    name: 'Rice 18',
    category: 'Rice',
    restaurant: 'Tasty Bites',
    price: 9.04,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/rice/rice19.jpg',
  },
  {
    id: 19,
    name: 'Samosa 19',
    category: 'Samosa',
    restaurant: 'Tasty Bites',
    price: 12.43,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/samosa/samosa1.jpg',
  },
  {
    id: 20,
    name: 'Rice 20',
    category: 'Rice',
    restaurant: 'Foodie Hub',
    price: 11.11,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/rice/rice1.jpg',
  },
  {
    id: 21,
    name: 'Samosa 21',
    category: 'Samosa',
    restaurant: 'Urban Kitchen',
    price: 13.01,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/samosa/samosa14.jpg',
  },
  {
    id: 22,
    name: 'Idly 22',
    category: 'Idly',
    restaurant: 'Belly Bliss',
    price: 12.3,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/idly/idly32.jpg',
  },
  {
    id: 23,
    name: 'Biryani 23',
    category: 'Biryani',
    restaurant: 'Urban Kitchen',
    price: 12.08,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/biryani/biryani29.jpg',
  },
  {
    id: 24,
    name: 'Dosa 24',
    category: 'Dosa',
    restaurant: 'Foodie Hub',
    price: 13.2,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/dosa/dosa28.jpg',
  },
  {
    id: 25,
    name: 'Pizza 25',
    category: 'Pizza',
    restaurant: 'Foodie Hub',
    price: 19.26,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/pizza/pizza46.jpg',
  },
  {
    id: 26,
    name: 'Burger 26',
    category: 'Burger',
    restaurant: 'Tasty Bites',
    price: 15.97,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/burger/burger27.jpg',
  },
  {
    id: 27,
    name: 'Samosa 27',
    category: 'Samosa',
    restaurant: 'Belly Bliss',
    price: 10.82,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/samosa/samosa46.jpg',
  },
  {
    id: 28,
    name: 'Burger 28',
    category: 'Burger',
    restaurant: 'Tasty Bites',
    price: 16.05,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/burger/burger28.jpg',
  },
  {
    id: 29,
    name: 'Pizza 29',
    category: 'Pizza',
    restaurant: 'Delish Diner',
    price: 8.89,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/pizza/pizza12.jpg',
  },
  {
    id: 30,
    name: 'Rice 30',
    category: 'Rice',
    restaurant: 'Tasty Bites',
    price: 13.2,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/rice/rice28.jpg',
  },
  {
    id: 31,
    name: 'Pizza 31',
    category: 'Pizza',
    restaurant: 'Tasty Bites',
    price: 19.25,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/pizza/pizza1.jpg',
  },
  {
    id: 32,
    name: 'Burger 32',
    category: 'Burger',
    restaurant: 'Tasty Bites',
    price: 15.74,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/burger/burger30.jpg',
  },
  {
    id: 33,
    name: 'Pizza 33',
    category: 'Pizza',
    restaurant: 'Belly Bliss',
    price: 16.9,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/pizza/pizza48.jpg',
  },
  {
    id: 34,
    name: 'Rice 34',
    category: 'Rice',
    restaurant: 'Delish Diner',
    price: 15.36,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/rice/rice16.jpg',
  },
  {
    id: 35,
    name: 'Idly 35',
    category: 'Idly',
    restaurant: 'Foodie Hub',
    price: 8.08,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/idly/idly8.jpg',
  },
  {
    id: 36,
    name: 'Burger 36',
    category: 'Burger',
    restaurant: 'Belly Bliss',
    price: 11.62,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/burger/burger21.jpg',
  },
  {
    id: 37,
    name: 'Pasta 37',
    category: 'Pasta',
    restaurant: 'Tasty Bites',
    price: 6.52,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/pasta/pasta28.jpg',
  },
  {
    id: 38,
    name: 'Idly 38',
    category: 'Idly',
    restaurant: 'Urban Kitchen',
    price: 11.25,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/idly/idly40.jpg',
  },
  {
    id: 39,
    name: 'Rice 39',
    category: 'Rice',
    restaurant: 'Delish Diner',
    price: 19.38,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/rice/rice42.jpg',
  },
  {
    id: 40,
    name: 'Dosa 40',
    category: 'Dosa',
    restaurant: 'Urban Kitchen',
    price: 8.62,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/dosa/dosa9.jpg',
  },
  {
    id: 41,
    name: 'Samosa 41',
    category: 'Samosa',
    restaurant: 'Tasty Bites',
    price: 11.9,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/samosa/samosa25.jpg',
  },
  {
    id: 42,
    name: 'Dosa 42',
    category: 'Dosa',
    restaurant: 'Foodie Hub',
    price: 11.34,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/dosa/dosa28.jpg',
  },
  {
    id: 43,
    name: 'Dessert 43',
    category: 'Dessert',
    restaurant: 'Tasty Bites',
    price: 12.63,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/dessert/dessert48.jpg',
  },
  {
    id: 44,
    name: 'Rice 44',
    category: 'Rice',
    restaurant: 'Tasty Bites',
    price: 9.48,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/rice/rice19.jpg',
  },
  {
    id: 45,
    name: 'Burger 45',
    category: 'Burger',
    restaurant: 'Delish Diner',
    price: 7.2,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/burger/burger46.jpg',
  },
  {
    id: 46,
    name: 'Rice 46',
    category: 'Rice',
    restaurant: 'Foodie Hub',
    price: 16.93,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/rice/rice50.jpg',
  },
  {
    id: 47,
    name: 'Dessert 47',
    category: 'Dessert',
    restaurant: 'Delish Diner',
    price: 14.31,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/dessert/dessert9.jpg',
  },
  {
    id: 48,
    name: 'Pizza 48',
    category: 'Pizza',
    restaurant: 'Foodie Hub',
    price: 5.22,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/pizza/pizza29.jpg',
  },
  {
    id: 49,
    name: 'Dessert 49',
    category: 'Dessert',
    restaurant: 'Tasty Bites',
    price: 16.06,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/dessert/dessert47.jpg',
  },
  {
    id: 50,
    name: 'Biryani 50',
    category: 'Biryani',
    restaurant: 'Delish Diner',
    price: 6.73,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/biryani/biryani22.jpg',
  },
  {
    id: 51,
    name: 'Biryani 51',
    category: 'Biryani',
    restaurant: 'Delish Diner',
    price: 19.26,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/biryani/biryani40.jpg',
  },
  {
    id: 52,
    name: 'Burger 52',
    category: 'Burger',
    restaurant: 'Foodie Hub',
    price: 19.91,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/burger/burger36.jpg',
  },
  {
    id: 53,
    name: 'Dosa 53',
    category: 'Dosa',
    restaurant: 'Belly Bliss',
    price: 7.06,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/dosa/dosa49.jpg',
  },
  {
    id: 54,
    name: 'Rice 54',
    category: 'Rice',
    restaurant: 'Urban Kitchen',
    price: 9.75,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/rice/rice29.jpg',
  },
  {
    id: 55,
    name: 'Biryani 55',
    category: 'Biryani',
    restaurant: 'Urban Kitchen',
    price: 11.55,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/biryani/biryani47.jpg',
  },
  {
    id: 56,
    name: 'Pizza 56',
    category: 'Pizza',
    restaurant: 'Delish Diner',
    price: 15.88,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/pizza/pizza6.jpg',
  },
  {
    id: 57,
    name: 'Pasta 57',
    category: 'Pasta',
    restaurant: 'Foodie Hub',
    price: 8.81,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/pasta/pasta32.jpg',
  },
  {
    id: 58,
    name: 'Biryani 58',
    category: 'Biryani',
    restaurant: 'Delish Diner',
    price: 17.97,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/biryani/biryani46.jpg',
  },
  {
    id: 59,
    name: 'Biryani 59',
    category: 'Biryani',
    restaurant: 'Delish Diner',
    price: 12.48,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/biryani/biryani9.jpg',
  },
  {
    id: 60,
    name: 'Pizza 60',
    category: 'Pizza',
    restaurant: 'Belly Bliss',
    price: 12.36,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/pizza/pizza16.jpg',
  },
  {
    id: 61,
    name: 'Idly 61',
    category: 'Idly',
    restaurant: 'Belly Bliss',
    price: 15.91,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/idly/idly18.jpg',
  },
  {
    id: 62,
    name: 'Pizza 62',
    category: 'Pizza',
    restaurant: 'Belly Bliss',
    price: 16.9,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/pizza/pizza30.jpg',
  },
  {
    id: 63,
    name: 'Idly 63',
    category: 'Idly',
    restaurant: 'Urban Kitchen',
    price: 14.3,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/idly/idly12.jpg',
  },
  {
    id: 64,
    name: 'Dosa 64',
    category: 'Dosa',
    restaurant: 'Tasty Bites',
    price: 16.55,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/dosa/dosa1.jpg',
  },
  {
    id: 65,
    name: 'Pasta 65',
    category: 'Pasta',
    restaurant: 'Tasty Bites',
    price: 19.36,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/pasta/pasta20.jpg',
  },
  {
    id: 66,
    name: 'Biryani 66',
    category: 'Biryani',
    restaurant: 'Foodie Hub',
    price: 8.47,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/biryani/biryani8.jpg',
  },
  {
    id: 67,
    name: 'Samosa 67',
    category: 'Samosa',
    restaurant: 'Belly Bliss',
    price: 17.68,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/samosa/samosa38.jpg',
  },
  {
    id: 68,
    name: 'Pasta 68',
    category: 'Pasta',
    restaurant: 'Belly Bliss',
    price: 16.46,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/pasta/pasta35.jpg',
  },
  {
    id: 69,
    name: 'Butter Chicken 69',
    category: 'Butter-Chicken',
    restaurant: 'Delish Diner',
    price: 9.67,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url:
      'https://foodish-api.com/images/butter-chicken/butter-chicken17.jpg',
  },
  {
    id: 70,
    name: 'Biryani 70',
    category: 'Biryani',
    restaurant: 'Foodie Hub',
    price: 13.5,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/biryani/biryani12.jpg',
  },
  {
    id: 71,
    name: 'Pasta 71',
    category: 'Pasta',
    restaurant: 'Urban Kitchen',
    price: 16.14,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/pasta/pasta9.jpg',
  },
  {
    id: 72,
    name: 'Butter Chicken 72',
    category: 'Butter-Chicken',
    restaurant: 'Urban Kitchen',
    price: 11.08,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url:
      'https://foodish-api.com/images/butter-chicken/butter-chicken15.jpg',
  },
  {
    id: 73,
    name: 'Biryani 73',
    category: 'Biryani',
    restaurant: 'Delish Diner',
    price: 10.43,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/biryani/biryani26.jpg',
  },
  {
    id: 74,
    name: 'Idly 74',
    category: 'Idly',
    restaurant: 'Urban Kitchen',
    price: 13.32,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/idly/idly39.jpg',
  },
  {
    id: 75,
    name: 'Butter Chicken 75',
    category: 'Butter-Chicken',
    restaurant: 'Urban Kitchen',
    price: 17.72,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url:
      'https://foodish-api.com/images/butter-chicken/butter-chicken42.jpg',
  },
  {
    id: 76,
    name: 'Samosa 76',
    category: 'Samosa',
    restaurant: 'Urban Kitchen',
    price: 13.07,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/samosa/samosa34.jpg',
  },
  {
    id: 77,
    name: 'Burger 77',
    category: 'Burger',
    restaurant: 'Belly Bliss',
    price: 6.66,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/burger/burger36.jpg',
  },
  {
    id: 78,
    name: 'Idly 78',
    category: 'Idly',
    restaurant: 'Tasty Bites',
    price: 8.82,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/idly/idly25.jpg',
  },
  {
    id: 79,
    name: 'Biryani 79',
    category: 'Biryani',
    restaurant: 'Urban Kitchen',
    price: 14.02,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/biryani/biryani43.jpg',
  },
  {
    id: 80,
    name: 'Samosa 80',
    category: 'Samosa',
    restaurant: 'Foodie Hub',
    price: 15.52,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/samosa/samosa7.jpg',
  },
  {
    id: 81,
    name: 'Rice 81',
    category: 'Rice',
    restaurant: 'Foodie Hub',
    price: 12.81,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/rice/rice36.jpg',
  },
  {
    id: 82,
    name: 'Pizza 82',
    category: 'Pizza',
    restaurant: 'Urban Kitchen',
    price: 16.77,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/pizza/pizza20.jpg',
  },
  {
    id: 83,
    name: 'Dosa 83',
    category: 'Dosa',
    restaurant: 'Belly Bliss',
    price: 13.76,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/dosa/dosa15.jpg',
  },
  {
    id: 84,
    name: 'Dosa 84',
    category: 'Dosa',
    restaurant: 'Belly Bliss',
    price: 6.0,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url: 'https://foodish-api.com/images/dosa/dosa1.jpg',
  },
  {
    id: 85,
    name: 'Pasta 85',
    category: 'Pasta',
    restaurant: 'Delish Diner',
    price: 14.15,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/pasta/pasta21.jpg',
  },
  {
    id: 86,
    name: 'Dosa 86',
    category: 'Dosa',
    restaurant: 'Belly Bliss',
    price: 13.7,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/dosa/dosa33.jpg',
  },
  {
    id: 87,
    name: 'Rice 87',
    category: 'Rice',
    restaurant: 'Urban Kitchen',
    price: 6.23,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/rice/rice34.jpg',
  },
  {
    id: 88,
    name: 'Pasta 88',
    category: 'Pasta',
    restaurant: 'Urban Kitchen',
    price: 17.76,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/pasta/pasta35.jpg',
  },
  {
    id: 89,
    name: 'Butter Chicken 89',
    category: 'Butter-Chicken',
    restaurant: 'Belly Bliss',
    price: 8.47,
    description: 'A delicious and freshly made dish to satisfy your cravings.',
    image_url:
      'https://foodish-api.com/images/butter-chicken/butter-chicken15.jpg',
  },
  {
    id: 90,
    name: 'Biryani 90',
    category: 'Biryani',
    restaurant: 'Belly Bliss',
    price: 6.87,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/biryani/biryani15.jpg',
  },
  {
    id: 91,
    name: 'Rice 91',
    category: 'Rice',
    restaurant: 'Urban Kitchen',
    price: 7.63,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/rice/rice31.jpg',
  },
  {
    id: 92,
    name: 'Burger 92',
    category: 'Burger',
    restaurant: 'Urban Kitchen',
    price: 18.91,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/burger/burger26.jpg',
  },
  {
    id: 93,
    name: 'Butter Chicken 93',
    category: 'Butter-Chicken',
    restaurant: 'Belly Bliss',
    price: 12.22,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url:
      'https://foodish-api.com/images/butter-chicken/butter-chicken31.jpg',
  },
  {
    id: 94,
    name: 'Pasta 94',
    category: 'Pasta',
    restaurant: 'Tasty Bites',
    price: 15.63,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/pasta/pasta42.jpg',
  },
  {
    id: 95,
    name: 'Pasta 95',
    category: 'Pasta',
    restaurant: 'Belly Bliss',
    price: 7.38,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/pasta/pasta10.jpg',
  },
  {
    id: 96,
    name: 'Samosa 96',
    category: 'Samosa',
    restaurant: 'Belly Bliss',
    price: 9.52,
    description: 'A must-try for food lovers, served hot and fresh.',
    image_url: 'https://foodish-api.com/images/samosa/samosa48.jpg',
  },
  {
    id: 97,
    name: 'Pasta 97',
    category: 'Pasta',
    restaurant: 'Foodie Hub',
    price: 6.79,
    description:
      'Prepared with authentic ingredients and bursting with flavor.',
    image_url: 'https://foodish-api.com/images/pasta/pasta49.jpg',
  },
  {
    id: 98,
    name: 'Rice 98',
    category: 'Rice',
    restaurant: 'Belly Bliss',
    price: 11.32,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/rice/rice12.jpg',
  },
  {
    id: 99,
    name: 'Dosa 99',
    category: 'Dosa',
    restaurant: 'Delish Diner',
    price: 14.81,
    description: 'Perfectly cooked with a blend of exotic spices.',
    image_url: 'https://foodish-api.com/images/dosa/dosa27.jpg',
  },
  {
    id: 100,
    name: 'Samosa 100',
    category: 'Samosa',
    restaurant: 'Belly Bliss',
    price: 17.21,
    description: "Enjoy this chef's special from our top-rated kitchen.",
    image_url: 'https://foodish-api.com/images/samosa/samosa21.jpg',
  },
];
